# Generated by Django 5.1.4 on 2025-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
