# Generated by Django 5.1.4 on 2025-01-08 12:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_receipe_is_deleted_receipe_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='receipe',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
