# Generated by Django 5.1.4 on 2025-01-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_studentmanager_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentManager',
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
